from settings import *

SC4G_BASIC_AUTH_TOKEN = ''
SC4G_FILES_URL = ''

ZOHO_AUTH_TOKEN = ''

DEFAULT_FROM_EMAIL = ''
EMAIL_HOST_USER = ''
EMAIL_HOST= ''
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_PASSWORD = ''
